name: Build Lighting Single EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt
          pip install pyinstaller # 确保安装了打包工具

      - name: 确保 config 文件夹存在
        shell: cmd
        run: if not exist config mkdir config

      - name: 执行单文件打包
        run: |
          pyinstaller Lighting_Control_System.spec

      - name: 上传成品 EXE
        uses: actions/upload-artifact@v4
        with:
          name: Lighting_System_Standalone
          path: dist/*.exe # 自动抓取生成的那唯一一个大 EXE
